2024-02-21 18:37:30.351 | ERROR    | __main__:get_book_total_price:110 - Erreur lors de la requÃªte HTTP : HTTPSConnectionPool(host='books.toscrape.com', port=443): Max retries exceeded with url: /catalogue/feathers-displays-of-brilliant-plumage_695/index.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f04ebb64070>: Failed to establish a new connection: [Errno 111] Connection refused'))
